-- Tabela PAUTA
CREATE TABLE PAUTA (
    ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    TITULO VARCHAR(255) NOT NULL,
    DESCRICAO VARCHAR(255)
);

INSERT INTO PAUTA (TITULO, DESCRICAO) VALUES
('Votação Reforma Interna', 'Decidir sobre nova política de trabalho remoto'),
('Nova Sede Administrativa', 'Avaliar aquisição de novo imóvel'),
('Revisão do Estatuto', 'Propor mudanças nas regras internas');

-- Tabela SESSAO_VOTACAO
CREATE TABLE SESSAO_VOTACAO (
    ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    DATA_ABERTURA TIMESTAMP NOT NULL,
    DATA_FECHAMENTO TIMESTAMP NOT NULL,
    PAUTA_ID BIGINT NOT NULL UNIQUE,
    FOREIGN KEY (PAUTA_ID) REFERENCES PAUTA(ID)
);

INSERT INTO SESSAO_VOTACAO (DATA_ABERTURA, DATA_FECHAMENTO, PAUTA_ID) VALUES
(TIMESTAMP '2025-05-19 08:00:00', TIMESTAMP '2025-05-19 08:30:00', 1),
(TIMESTAMP '2025-05-19 09:00:00', TIMESTAMP '2025-05-19 10:00:00', 2);

-- Tabela VOTO
CREATE TABLE VOTO (
    ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    SESSAO_ID BIGINT NOT NULL,
    CPF_ASSOCIADO VARCHAR(255) NOT NULL UNIQUE,
    VOTO VARCHAR(3) CHECK (VOTO IN ('SIM', 'NAO')),
    FOREIGN KEY (SESSAO_ID) REFERENCES SESSAO_VOTACAO(ID)
);

INSERT INTO VOTO (SESSAO_ID, CPF_ASSOCIADO, VOTO) VALUES
(1, '12345678900', 'SIM'),
(1, '11122233344', 'NAO'),
(2, '99988877766', 'SIM');